name: Deploy Kitchensink

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: deploy-kitchensink
  cancel-in-progress: false

jobs:
  deploy-kitchensink:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.12.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Check pnpm
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy Sanity App
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN_DEPLOY }}
        run: pnpm run deploy:kitchensink
